import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('employees').del();

  // Inserts seed entries
  await knex('employees').insert([
    {
      name: 'Alice Johnson',
      age: 32,
      designation: 'Senior Software Engineer',
      hiring_date: '2021-03-15',
      date_of_birth: '1992-05-20',
      salary: 95000.00,
      photo_path: 'uploads/alice-johnson.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Robert Martinez',
      age: 45,
      designation: 'HR Manager',
      hiring_date: '2019-07-01',
      date_of_birth: '1979-11-10',
      salary: 85000.00,
      photo_path: 'uploads/robert-martinez.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Emily Chen',
      age: 28,
      designation: 'Junior Accountant',
      hiring_date: '2022-09-12',
      date_of_birth: '1996-03-25',
      salary: 52000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Michael Brown',
      age: 38,
      designation: 'Sales Executive',
      hiring_date: '2020-05-20',
      date_of_birth: '1986-08-14',
      salary: 68000.00,
      photo_path: 'uploads/michael-brown.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Sarah Williams',
      age: 41,
      designation: 'Marketing Director',
      hiring_date: '2018-02-28',
      date_of_birth: '1983-12-05',
      salary: 110000.00,
      photo_path: 'uploads/sarah-williams.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'David Lee',
      age: 29,
      designation: 'Software Engineer',
      hiring_date: '2023-01-10',
      date_of_birth: '1995-07-18',
      salary: 78000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Jessica Taylor',
      age: 35,
      designation: 'Product Manager',
      hiring_date: '2020-11-15',
      date_of_birth: '1989-04-22',
      salary: 102000.00,
      photo_path: 'uploads/jessica-taylor.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'James Anderson',
      age: 52,
      designation: 'Chief Financial Officer',
      hiring_date: '2017-06-01',
      date_of_birth: '1972-09-30',
      salary: 155000.00,
      photo_path: 'uploads/james-anderson.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Maria Garcia',
      age: 26,
      designation: 'UI/UX Designer',
      hiring_date: '2023-08-05',
      date_of_birth: '1998-01-12',
      salary: 62000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Christopher Wilson',
      age: 43,
      designation: 'DevOps Engineer',
      hiring_date: '2019-10-22',
      date_of_birth: '1981-06-08',
      salary: 92000.00,
      photo_path: 'uploads/christopher-wilson.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Linda Thompson',
      age: 39,
      designation: 'Senior Accountant',
      hiring_date: '2020-03-18',
      date_of_birth: '1985-10-15',
      salary: 72000.00,
      photo_path: 'uploads/linda-thompson.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Daniel Moore',
      age: 31,
      designation: 'Business Analyst',
      hiring_date: '2021-12-01',
      date_of_birth: '1993-02-28',
      salary: 70000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Patricia Harris',
      age: 47,
      designation: 'Operations Manager',
      hiring_date: '2018-08-14',
      date_of_birth: '1977-05-03',
      salary: 98000.00,
      photo_path: 'uploads/patricia-harris.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Kevin Clark',
      age: 33,
      designation: 'QA Engineer',
      hiring_date: '2022-04-25',
      date_of_birth: '1991-11-19',
      salary: 65000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Jennifer Rodriguez',
      age: 36,
      designation: 'Project Manager',
      hiring_date: '2020-07-08',
      date_of_birth: '1988-08-27',
      salary: 88000.00,
      photo_path: 'uploads/jennifer-rodriguez.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Thomas White',
      age: 42,
      designation: 'Sales Manager',
      hiring_date: '2019-01-20',
      date_of_birth: '1982-03-16',
      salary: 95000.00,
      photo_path: 'uploads/thomas-white.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Nancy Lewis',
      age: 27,
      designation: 'Content Writer',
      hiring_date: '2023-05-15',
      date_of_birth: '1997-09-07',
      salary: 48000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Steven Hall',
      age: 50,
      designation: 'IT Security Specialist',
      hiring_date: '2018-11-30',
      date_of_birth: '1974-07-22',
      salary: 105000.00,
      photo_path: 'uploads/steven-hall.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Karen Young',
      age: 34,
      designation: 'Customer Support Lead',
      hiring_date: '2021-06-10',
      date_of_birth: '1990-12-11',
      salary: 58000.00,
      photo_path: 'uploads/karen-young.jpg',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      name: 'Brian King',
      age: 25,
      designation: 'Junior Developer',
      hiring_date: '2024-02-01',
      date_of_birth: '1999-04-05',
      salary: 55000.00,
      photo_path: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
}
